### PR TITLE
Linters setup

### PR DESCRIPTION
**Pull request by edygar**
This PR intents to setup the Linter tools.

- [x] Absolute Imports
- [x] Flow
- [x] Tests setup
- [x] ESLint
- ~Docs~
- ~StyleLint~

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Are the configurations all done @edygar?

**Comment by edygar** [comment]
@WendellAdriel, not yet, but I'll check this [list](https://github.com/instreets/instreets-app/pull/1#issue-211194025) as I configure each step.

**Comment by WendellAdriel** [comment]
Thanks @edygar

**Comment by edygar** [comment]
So, `stylelint` inside JS files is still somewhat unstable, it wouldn't provide useful feedbacks and it could cause some struggle with editor, so for now it is aborted.

About the Docs, I will let the setup mature a little before start. 

So, @WendellAdriel, I'm just waiting your approve.

**Pull request merged**
